### ISSUE TITLE
Ifh-Bíff Efreet legality in question

### ISSUE THREAD

**Issue by carmlives** [silasary/Penny-Dreadful-Discord-Bot#9392]
On scyfall and https://pennydreadfulmagic.com/deckcheck/  [Ifh-Bíff Efreet] is legal in penny dreadful. When I cast it on MTGO I get a message saying its not legal. Please confirm its legality and fix on PD bot. Thank you

**Comment by bakert** [comment]
Ifh-Bíff Efreet is legal. The final arbiter of legality is always http://pdmtgo.com/legal_cards.txt

I expect the accent on the I is misrendered in MTGO or otherwise confusing the bot.

Until that is fixed you can report the result of league games involving the card at https://pennydreadfulmagic.com/report/
